image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
#    - npm run test

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "rm -rf ~/deployments/sw/www/json-schema-validator"
    - scp -r -v -o StrictHostKeyChecking=no . tc_spo01@wp-p1m2-3d:~/deployments/sw/www/json-schema-validator
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "~/config/deploy_validator.sh"
  only:
    - master
