image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
#    - npm run test

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$NOAH_LOGIN_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli rm -rf /nfs/spot/data/test/biosamples/json-schema-validator
    - scp -r -v -o StrictHostKeyChecking=no . isuru@ebi-cli:/nfs/spot/data/test/biosamples/json-schema-validator
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli become tc_spo01 "ssh wp-np2-40 'rm -rf /mnt/data/biosamples/sw/wwwdev/json-schema-validator'"
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli become tc_spo01 "ssh wp-np2-40 'scp -r ebi-cli:/nfs/spot/data/test/biosamples/json-schema-validator /mnt/data/biosamples/sw/wwwdev/json-schema-validator'"
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli become tc_spo01 "ssh wp-np2-40 'export NODE_HOME=/mnt/data/biosamples/servers/node-v14.15.1-linux-x64'"
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli become tc_spo01 "ssh wp-np2-40 'export PATH=$PATH:$NODE_HOME/bin'"
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli become tc_spo01 "ssh wp-np2-40 'nohup node /mnt/data/biosamples/sw/wwwdev/json-schema-validator/src/server.js &'"
  only:
    - master
